### ISSUE TITLE
Migrate tests to test/unit

### ISSUE THREAD

**Issue by gma** [gma/nesta#32]
I much prefer minitest to Rspec, primarily because upgrading to the latest Rspec API isn't something I'm prepared to spend my free time doing.

We also need to split unit tests from integration tests, and separate the integration tests into those that can be expected to pass for any theme, and those that are specific to the default theme.

## Tasks

- [x] Write rake tasks to execute the tests (`rake test:unit`, `rake test:integration`, `rake test`)
- [x] Port spec files to minitest:
  - [x] atom_spec.rb
  - [x] commands/*_spec.rb
  - [x] config_spec.rb
  - [x] models_spec.rb
  - [x] overrides_spec.rb
  - [x] page_spec.rb
  - [x] path_spec.rb
  - [x] plugin_spec.rb
  - [x] sitemap_spec.rb
- [x] Remove `rspec` and `test/unit` gems.
- [x] Remove methods used only by Rspec from new `ModelFactory`.
- [x] Refactor `ModelFactory`:
  - [x] Replace `create_*` methods with simple `create(:type...)` approach.
  - [x] Add auto-incrementing sequence to file paths (get it working on all writers).
  - [x] Go through each test file, removing unnecessarily specified paths.
- [x] Consider whether to break tests' dependency on contents of default theme.

## Stack

After merging branch to `master`:
- [ ] Rename `@@page_cache` to `@@model_cache`.
- [x] Get rid of/refactor `delete_page` in model factory.
- [ ] Make `Page#link_text` return "Home" for home page, if not otherwise defined.
- [ ] Remove `hgroup` tag from default theme.
